print("Installing the latest version of required packages:")
install.packages("shiny", repos = "https://cran.csiro.au/")
install.packages("shinythemes", repos = "https://cran.csiro.au/")
install.packages("shinydashboard", repos = "https://cran.csiro.au/")
install.packages("tidyverse", repos = "https://cran.csiro.au/")
install.packages("rioja", repos = "https://cran.csiro.au/")
install.packages("vegan", repos = "https://cran.csiro.au/")
install.packages("analogue", repos = "https://cran.csiro.au/")
install.packages("neotoma", repos = "https://cran.csiro.au/")
install.packages("iNEXT", repos = "https://cran.csiro.au/")
install.packages("DT", repos = "https://cran.csiro.au/")
install.packages("DBI", repos = "https://cran.csiro.au/")
install.packages("dplyr", repos = "https://cran.csiro.au/")
install.packages("dbplyr", repos = "https://cran.csiro.au/")
install.packages("data.table", repos = "https://cran.csiro.au/")
install.packages("devtools", repos = "https://cran.csiro.au/")
library(devtools)
devtools::install_github("rstudio/pool")