print("Installing the latest version of required packages:")
install.packages("shiny")
install.packages("shinythemes")
install.packages("shinydashboard")
install.packages("tidyverse")
install.packages("rioja")
install.packages("vegan")
install.packages("analogue")
install.packages("neotoma")
install.packages("iNEXT")
install.packages("DT")
install.packages("DBI")
install.packages("dplyr")
install.packages("dbplyr")
install.packages("devtools")
library(devtools)
devtools::install_github("rstudio/pool")